name: main

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build extension & upload artifacts
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Chmod
        run: chmod +x build.sh
      - name: Zip
        run: ./zip.sh
      - uses: cardinalby/webext-buildtools-chrome-crx-action@v2
        with:
          zipFilePath: 'foxford-tools.zip'
          crxFilePath: 'foxford-tools.crx'
          privateKey: ${{ secrets.CHROME_CRX_PRIVATE_KEY }}
