name: main

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    name: Lint, format, type-check and test
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - name: Install pnpm
        uses: pnpm/action-setup@v6
      - name: Install dependencies
        run: pnpm install
      - name: Run lint
        run: pnpm run lint
      - name: Check formatting
        run: pnpm run format:check
      - name: Type-check
        run: pnpm run type-check
      - name: Run tests
        run: pnpm run test

  build:
    runs-on: ubuntu-latest
    name: Build and upload extension
    needs: checks
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - name: Install pnpm
        uses: pnpm/action-setup@v6
      - name: Install dependencies
        run: pnpm install
      - name: Zip extensions
        run: pnpm run zip && pnpm run zip:firefox
      - name: Collect artifacts
        run: |
          echo "CHROME_ZIP=$(ls .output/*-chrome.zip)" >> $GITHUB_ENV
          echo "FIREFOX_ZIP=$(ls .output/*-firefox.zip)" >> $GITHUB_ENV
          echo "SOURCES_ZIP=$(ls .output/*-sources.zip)" >> $GITHUB_ENV
      - name: Upload Chrome artifact
        uses: actions/upload-artifact@v7
        with:
          name: chrome
          path: ${{ env.CHROME_ZIP }}
          archive: false
      - name: Upload Firefox artifact
        uses: actions/upload-artifact@v7
        with:
          name: firefox
          path: ${{ env.FIREFOX_ZIP }}
          archive: false
      - name: Upload Firefox sources artifact
        uses: actions/upload-artifact@v7
        with:
          name: firefox-sources
          path: ${{ env.SOURCES_ZIP }}
          archive: false
