name: main

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Upload extension as zip
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upload extension as zip
        uses: actions/upload-artifact@v3
        with:
          name: src
          path: 'src/'
      - name: Upload extension as zip for firefox
        uses: actions/upload-artifact@v3
        with:
          name: firefox-src
          path: 'firefox-src.zip'
