name: main

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build extension
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: cd build && ./build.sh
