name: main

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build extension & upload artifacts
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: cd build && ./build.sh
      - name: Change output permission
        run: sudo chmod -R 777 output/
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: result-artifact
          path: ./foxford-tools.crx
